from __future__ import annotations

import json
from pathlib import Path

import click

from .analysis.detect_clusters import detect
from .analysis.traffic import estimate
from .codegen.emit import emit
from .ir.shapes import ShapePropError, propagate
from .ir.trace import TracingError, trace
from .loader import LoadError, build_example_input, load, parse_dtype, parse_shape
from .report import console as report
from .report.json_out import build_payload
from .sourcemap.apply import ApplyError, apply_diffs
from .sourcemap.diff import build as build_diff
from .sourcemap.diff import call_expression
from .sourcemap.provenance import MappingQuality, resolve, user_variable_names
from .validate.bench import gpu_available, validate

KERNEL_FILE_HEADER = """\
# Generated by fusion-advisor. Review before use.
#
# Forward-only for now: backward kernels are not generated yet, so .backward()
# through one of these raises NotImplementedError until they are.
import torch
import triton
import triton.language as tl

"""

KERNEL_MODULE = "fusion_kernels"  # --apply writes this next to the model, so the import resolves


def _fail(msg: str):
    raise click.ClickException(msg)


def _analyze(model, example_inputs):
    """Trace and shape-prop, turning library errors into CLI errors."""
    try:
        gm = trace(model)
    except TracingError as e:
        _fail(str(e))
    try:
        specs = propagate(gm, *example_inputs)
    except ShapePropError as e:
        _fail(str(e))
    return gm, specs


def _kernel_text(kernels) -> str:
    body = "\n\n".join(f"{k.kernel_source}\n\n{k.wrapper_source}" for k in kernels)
    return f"{KERNEL_FILE_HEADER}{body}\n"


def _write_kernel(out_dir: Path, kernel) -> Path:
    path = out_dir / f"{kernel.name}.py"
    path.write_text(_kernel_text([kernel]))
    return path


def _measure(clusters, kernels, gm, specs, vs_inductor: bool) -> list:
    """Compile, verify and benchmark each kernel; None per cluster without a GPU."""
    if not gpu_available():
        report.console.print(
            "\nNot measured - numerics and speedup need a CUDA GPU and triton.", style="dim"
        )
        return [None] * len(clusters)

    report.console.print("\n[bold]Measured[/bold]")
    results = []
    for c, kernel in zip(clusters, kernels, strict=True):
        if kernel is None:  # emit failed, nothing to measure
            results.append(None)
            continue
        result = validate(kernel, c, gm, specs, vs_inductor=vs_inductor)
        report.render_validation(c, result)
        results.append(result)
    return results


def _apply_edits(loaded, kernels, diffs) -> None:
    """Write one importable kernel module next to the model, then rewrite the model."""
    usable = [(k, d) for k, d in zip(kernels, diffs, strict=True) if k and d]
    if not usable:
        report.console.print("\nNo EXACT diff to apply; model left unchanged.", style="yellow")
        return

    model_path = Path(loaded.source_path)
    report.console.print(
        "\nKernels are forward-only for now; .backward() through one raises "
        "until backward codegen lands.",
        style="yellow",
    )
    if not click.confirm(
        f"Rewrite {model_path.name} in place ({len(usable)} edit(s))?", default=False
    ):
        return

    names = ", ".join(k.name for k, _ in usable)
    try:
        rewritten = apply_diffs(
            loaded.source_text, [d for _, d in usable], f"from {KERNEL_MODULE} import {names}"
        )
    except ApplyError as e:
        _fail(str(e))

    module_path = model_path.parent / f"{KERNEL_MODULE}.py"
    module_path.write_text(_kernel_text([k for k, _ in usable]))
    model_path.write_text(rewritten)

    report.console.print(f"\nwrote [bold]{module_path.name}[/bold]")
    report.console.print(f"updated [bold]{model_path.name}[/bold] ({len(usable)} edit(s))")


@click.command()
@click.option("--model", required=True, help="Path to a .py file defining an nn.Module.")
@click.option("--model-class", default=None, help="Class name, if the file defines several.")
@click.option(
    "--input-shape",
    required=True,
    multiple=True,
    help="Example input shape, e.g. 4,128. Repeat for multi-input models.",
)
@click.option("--dtype", default="float32")
@click.option("--json", "json_out", default=None, help="Write machine-readable results here.")
@click.option("--explain-rejections", is_flag=True, help="Show why candidates were not fused.")
@click.option(
    "--vs-inductor",
    is_flag=True,
    help="Also benchmark torch.compile per cluster.",
)
@click.option("--out-dir", default=".", help="Where to write generated kernel files.")
@click.option(
    "--apply",
    "apply_edits",
    is_flag=True,
    help=(
        f"Apply the diffs to the model file after confirmation. "
        f"Writes a sibling {KERNEL_MODULE}.py."
    ),
)
def main(
    model, model_class, input_shape, dtype, json_out, explain_rejections, vs_inductor,
    out_dir, apply_edits,
):
    """Fusion Advisor: static fusion analysis for PyTorch models."""
    try:
        loaded = load(model, model_class)
        torch_dtype = parse_dtype(dtype)
        shapes = [parse_shape(s) for s in input_shape]
    except LoadError as e:
        _fail(str(e))

    example_inputs = [build_example_input(s, torch_dtype) for s in shapes]
    gm, specs = _analyze(loaded.module, example_inputs)

    all_nodes = list(gm.graph.nodes)
    clusters, rejections = detect(gm, specs)
    estimates = [estimate(c, specs) for c in clusters]
    ranges = [resolve(c, all_nodes) for c in clusters]

    report.console.print(
        f"[bold]{type(loaded.module).__name__}[/bold] "
        f"({len(all_nodes)} nodes, {len(clusters)} fusable cluster(s))\n"
    )
    report.render_clusters(clusters, estimates, ranges)
    if explain_rejections:
        report.render_rejections(rejections)

    var_names = user_variable_names(all_nodes, loaded.source_text)
    diffs = [None] * len(clusters)
    kernels = [None] * len(clusters)
    if clusters:
        out_path = Path(out_dir)
        if not apply_edits:
            out_path.mkdir(parents=True, exist_ok=True)

        for i, (c, rng) in enumerate(zip(clusters, ranges, strict=True)):
            try:
                kernels[i] = emit(c, specs)
            except (ValueError, AssertionError, KeyError) as e:
                report.console.print(f"cluster {c.index}: cannot emit - {e}", style="yellow")
                continue
            if not apply_edits:
                report.console.print(f"\nwrote [bold]{_write_kernel(out_path, kernels[i])}[/bold]")
            call = call_expression(kernels[i], c, var_names)
            if rng.quality is MappingQuality.EXACT and call:
                diffs[i] = build_diff(rng, kernels[i], loaded.source_text, call)
                report.render_diff(diffs[i])
            elif rng.quality is MappingQuality.EXACT:
                report.console.print(
                    f"\ncluster {c.index}: no safe diff - an input has no named variable "
                    f"in your source.",
                    style="dim",
                )
            else:
                report.render_unmapped(c, rng)

        if apply_edits:
            _apply_edits(loaded, kernels, diffs)

    validations = _measure(clusters, kernels, gm, specs, vs_inductor)

    if json_out:
        payload = build_payload(
            clusters, estimates, ranges, diffs, validations, rejections
        )
        Path(json_out).write_text(json.dumps(payload, indent=2))
        report.console.print(f"wrote {json_out}", style="dim")


if __name__ == "__main__":
    main()
